// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaddishRestaurant.Services.ProductAPI.DbContexts;

namespace RaddishRestaurant.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220624225608_SeedProducts")]
    partial class SeedProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("RaddishRestaurant.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Appetizer",
                            Description = "Filled with the freshest vegetables and deep fried in olive oil",
                            ImageUrl = "https://images.hindustantimes.com/rf/image_size_630x354/HT/p2/2020/08/02/Pictures/_604f7aa4-d439-11ea-bae0-701c4bed6ede.jpg",
                            Name = "Samosa",
                            Price = 15.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Main Dish",
                            Description = "Coconut Rice is a delicacy known for its unique and mouth watering taste. Why not give it a try",
                            ImageUrl = "https://www.allnigerianrecipes.com/wp-content/uploads/2019/03/white-coconut-rice.jpg",
                            Name = "Coconut Rice",
                            Price = 13.99
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Appetizer",
                            Description = "You can't have a enough of this sweet goodness rolled up in the freshest of dough.",
                            ImageUrl = "https://guardian.ng/wp-content/uploads/2017/07/choclate-icecream1.jpeg",
                            Name = "Sweet Pie",
                            Price = 7.7999999999999998
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Dessert",
                            Description = "Not like the ordinary icecream you come by everyday. Each scoop is filled with creamy goodness",
                            ImageUrl = "",
                            Name = "Chocolate Scoop",
                            Price = 10.99
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
